version: "3.8"

services:
  ingestion:
    build:
      context: ./ingestion
      dockerfile: Dockerfile
    container_name: hmas_ingestion
    ports:
      - "8000:8000"
    networks:
      - hmas_network

  perception:
    build:
      context: ./perception
      dockerfile: Dockerfile
    container_name: hmas_perception
    ports:
      - "8100:8100"
    depends_on:
      - ingestion
    networks:
      - hmas_network

  integration:
    build:
      context: ./integration
      dockerfile: Dockerfile
    container_name: hmas_integration
    ports:
      - "8200:8200"
    depends_on:
      - perception
    networks:
      - hmas_network

  routing:
    build:
      context: ./routing
      dockerfile: Dockerfile
    container_name: hmas_routing
    ports:
      - "8300:8300"
    depends_on:
      - integration
    networks:
      - hmas_network

  specialized:
    build:
      context: ./specialized
      dockerfile: Dockerfile
    container_name: hmas_specialized
    ports:
      - "8400:8400"
    depends_on:
      - routing
    networks:
      - hmas_network

  meta:
    build:
      context: ./meta
      dockerfile: Dockerfile
    container_name: hmas_meta
    ports:
      - "8301:8301"   # Meta now runs on port 8301
    depends_on:
      - specialized
    networks:
      - hmas_network

  memory:
    build:
      context: ./memory
      dockerfile: Dockerfile
    container_name: hmas_memory
    ports:
      - "8401:8401"
    depends_on:
      - meta
    networks:
      - hmas_network

  aggregation:
    build:
      context: ./aggregation
      dockerfile: Dockerfile
    container_name: hmas_aggregation
    ports:
      - "8500:8500"
    depends_on:
      - memory
    networks:
      - hmas_network

  feedback:
    build:
      context: ./feedback
      dockerfile: Dockerfile
    container_name: hmas_feedback
    ports:
      - "8600:8600"
    depends_on:
      - aggregation
    networks:
      - hmas_network

  monitoring:
    build:
      context: ./monitoring
      dockerfile: Dockerfile
    container_name: hmas_monitoring
    ports:
      - "8700:8700"
    depends_on:
      - feedback
    networks:
      - hmas_network

  graph_rl:
    build:
      context: ./graph_rl
      dockerfile: Dockerfile
    container_name: hmas_graph_rl
    ports:
      - "8800:8800"
    networks:
      - hmas_network

  comm_optimization:
    build:
      context: ./communication
      dockerfile: Dockerfile
    container_name: hmas_comm_optimization
    ports:
      - "8900:8900"
    networks:
      - hmas_network

  pipeline:
    build:
      context: ./pipelines
      dockerfile: Dockerfile
    container_name: hmas_pipeline
    ports:
      - "9000:9000"
    depends_on:
      - ingestion
      - perception
      - integration
      - routing
      - specialized
      - meta
      - memory
      - aggregation
      - feedback
      - monitoring
      - graph_rl
      - comm_optimization
    networks:
      - hmas_network

networks:
  hmas_network:
    driver: bridge
