# Development environment configuration for HMAS services

# Inherit from default configuration
_extends: default.yaml

# Environment settings
debug: true
testing: false
host: "0.0.0.0"
port: 8000
base_url: "http://localhost:8000"

# Database configuration
database:
  host: "localhost"
  port: 27017
  username: "dev_user"
  database: "hmas_dev"
  max_connections: 5
  timeout: 30.0
  ssl_enabled: false

# Redis configuration
redis:
  host: "localhost"
  port: 6379
  db: 0
  ssl_enabled: false

# Security configuration
security:
  token_expiry: 86400  # 24 hours for development
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8000"
  ssl_enabled: false

# Logging configuration
logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "logs/hmas_dev.log"
  rotate_size: 5242880  # 5MB
  rotate_count: 3
  json_format: false

# Monitoring configuration
monitoring:
  enabled: true
  prometheus_enabled: true
  metrics_port: 9090
  health_check_interval: 15
  tracing_enabled: true
  tracing_sample_rate: 1.0  # Sample all requests in development

# Resource limits
resource_limits:
  cpu_limit: "0.5"
  memory_limit: "512Mi"
  storage_limit: "5Gi"
  max_workers: 2
  request_timeout: 60  # Longer timeout for debugging

# Directories
temp_dir: "./tmp"
data_dir: "./data"
config_dir: "./config" 