apiVersion: v1
kind: Secret
metadata:
  name: hmas-secrets
  namespace: hmas
type: Opaque
data:
  # Database Credentials (base64 encoded)
  MONGODB_USERNAME: bW9uZ29kYl91c2Vy  # mongodb_user
  MONGODB_PASSWORD: bW9uZ29kYl9wYXNzd29yZA==  # mongodb_password
  
  # Redis Credentials (base64 encoded)
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmQ=  # redis_password
  
  # JWT Secret (base64 encoded)
  JWT_SECRET: and0X3NlY3JldF9rZXk=  # jwt_secret_key
  
  # API Keys (base64 encoded)
  OPENAI_API_KEY: b3BlbmFpX2FwaV9rZXk=  # openai_api_key
  HUGGINGFACE_API_KEY: aHVnZ2luZ2ZhY2VfYXBpX2tleQ==  # huggingface_api_key
  
  # TLS Certificates (base64 encoded)
  TLS_CERT: dGxzX2NlcnRpZmljYXRl  # tls_certificate
  TLS_KEY: dGxzX3ByaXZhdGVfa2V5  # tls_private_key
  
  # Encryption Keys (base64 encoded)
  ENCRYPTION_KEY: ZW5jcnlwdGlvbl9rZXk=  # encryption_key
  SIGNING_KEY: c2lnbmluZ19rZXk=  # signing_key 